pub mod activity_widget;
mod canvas_utils;
pub mod chart;
pub mod circle_widget;
pub mod general_exercise_info_elements;
pub mod graph;
pub mod new_widget;
pub mod pop_up;
pub mod progress;
pub mod shop;
pub mod social_elements;
pub mod stats;
pub mod widget_utils;
pub mod workout;
