pub mod activity_widget;
pub mod bmi_calculator;
mod canvas_utils;
pub mod chart_widget;
pub mod circle_widget;
pub mod general_exercise_info_elements;
pub mod new_widget;
pub mod pop_up;
pub mod preset_workout_rows;
pub mod progress_bar;
pub mod shop;
pub mod social_elements;
pub mod stats;
pub mod widget_utils;
pub mod workout;
pub mod animated_background_mod;
